import { createRouter, createWebHistory } from 'vue-router'

const router = createRouter({
  history: createWebHistory(),
  routes: [
    { path: '/', name: 'Dashboard', meta: { title: 'Dashboard' }, component: () => import('../views/DashboardView.vue') },
    { path: '/data', name: 'DataHub', meta: { title: 'Data' }, component: () => import('../views/DataHubView.vue') },
    { path: '/run-center', name: 'RunCenter', meta: { title: 'Run Center' }, component: () => import('../views/RunCenterView.vue') },
    { path: '/workbench', name: 'PlannerWorkbench', meta: { title: 'Planner Workbench' }, component: () => import('../views/PlannerWorkbenchView.vue') },
    { path: '/setup', name: 'Setup', meta: { title: 'Getting Started' }, component: () => import('../views/SetupView.vue') },
    { path: '/stock-projection', name: 'StockProjection', meta: { title: 'Stock Projection' }, component: () => import('../views/StockProjectionView.vue') },
    { path: '/inventory-projection', name: 'InventoryProjection', meta: { title: 'Inventory Projection' }, component: () => import('../views/InventoryProjectionView.vue') },
    { path: '/planning-grid', name: 'WeeklyPlanningGrid', meta: { title: 'Weekly Planning Grid' }, component: () => import('../views/WeeklyPlanningGridView.vue') },
    { path: '/sku-detail', name: 'SkuDetail', meta: { title: 'SKU Detail' }, component: () => import('../views/SkuDetailView.vue') },
    { path: '/planned-orders', name: 'PlannedOrders', meta: { title: 'Planned Orders' }, component: () => import('../views/PlannedOrdersView.vue') },
    { path: '/stock-position', name: 'StockPosition', meta: { title: 'Stock Position' }, component: () => import('../views/StockPositionBreakdownView.vue') },
    { path: '/exceptions', name: 'Exceptions', meta: { title: 'Exceptions' }, component: () => import('../views/ExceptionsView.vue') },
    { path: '/planning/scenario-manager', name: 'ScenarioManager', meta: { title: 'Scenario Manager' }, component: () => import('../views/ScenarioManagerView.vue') },
    { path: '/forecast/check', name: 'ForecastCheck', meta: { title: 'Forecast Check' }, component: () => import('../views/forecast/ForecastCheckView.vue') },
    { path: '/forecast/dashboard', name: 'ForecastDashboard', meta: { title: 'Forecast Dashboard' }, component: () => import('../views/forecast/ForecastDashboardView.vue') },
    { path: '/forecast/runs',      name: 'ForecastRuns',      meta: { title: 'Run Forecast' },          component: () => import('../views/forecast/ForecastRunsView.vue') },
    { path: '/forecast/scenarios', name: 'ForecastScenarios', meta: { title: 'Forecast Scenarios' }, component: () => import('../views/forecast/ForecastScenariosView.vue') },
    { path: '/forecast/exports',   name: 'ForecastExports',   meta: { title: 'Forecast Exports' },   component: () => import('../views/forecast/ForecastExportsView.vue') },
    {
      path: '/admin',
      name: 'Admin',
      meta: { title: 'Admin' },
      component: () => import('../views/AdminView.vue'),
      redirect: { name: 'AdminProducts' },
      children: [
        { path: 'products', name: 'AdminProducts', meta: { title: 'Admin · Products' }, component: () => import('../views/admin/AdminProductsTab.vue') },
        { path: 'products/:id', name: 'AdminProductDetail', meta: { title: 'Admin · Product' }, component: () => import('../views/admin/AdminProductDetailView.vue') },
        { path: 'warehouses', name: 'AdminWarehouses', meta: { title: 'Admin · Warehouses' }, component: () => import('../views/admin/AdminWarehousesTab.vue') },
        { path: 'warehouses/:id', name: 'AdminWarehouseDetail', meta: { title: 'Admin · Warehouse' }, component: () => import('../views/admin/AdminWarehouseDetailView.vue') },
        { path: 'suppliers', name: 'AdminSuppliers', meta: { title: 'Admin · Suppliers' }, component: () => import('../views/admin/AdminSuppliersTab.vue') },
        { path: 'suppliers/:id', name: 'AdminSupplierDetail', meta: { title: 'Admin · Supplier' }, component: () => import('../views/admin/AdminSupplierDetailView.vue') },
        { path: 'lanes', name: 'AdminLanes', meta: { title: 'Admin · Lanes' }, component: () => import('../views/admin/AdminLanesTab.vue') },
        { path: 'lanes/:id', name: 'AdminLaneDetail', meta: { title: 'Admin · Lane' }, component: () => import('../views/admin/AdminLaneDetailView.vue') },
        { path: 'policies', name: 'AdminPolicies', meta: { title: 'Settings · Stock Rules' }, component: () => import('../views/admin/AdminPoliciesTab.vue') },
        { path: 'policies/:id', name: 'AdminPolicyDetail', meta: { title: 'Settings · Stock Rule' }, component: () => import('../views/admin/AdminPolicyDetailView.vue') },
        { path: 'timelines', name: 'AdminTimelines', meta: { title: 'Admin · Timelines' }, component: () => import('../views/admin/AdminTimelinesView.vue') },
        { path: 'forecast-methods', name: 'AdminForecastMethods', meta: { title: 'Admin · Forecasting Methods' }, component: () => import('../views/admin/ForecastMethodsView.vue') },
        { path: 'forecast-engine', name: 'AdminForecastEngine', meta: { title: 'Settings · Forecast Settings' }, component: () => import('../views/admin/AdminForecastEngineTab.vue') },
        { path: 'settings', name: 'AdminSettings', meta: { title: 'Admin · Settings' }, component: () => import('../views/admin/AdminSettingsTab.vue') },
        { path: 'import-formats', name: 'AdminImportFormats', meta: { title: 'Admin · Import Formats' }, component: () => import('../views/admin/AdminImportFormatsTab.vue') },
        { path: 'warehouse-product-codes', name: 'AdminWarehouseProductCodes', meta: { title: 'Admin · Warehouse Product Codes' }, component: () => import('../views/admin/AdminWarehouseProductCodesTab.vue') },
        { path: 'data-management', name: 'AdminDataManagement', meta: { title: 'Admin · Data Management' }, component: () => import('../views/admin/AdminDataManagementView.vue') },
      ],
    },
    {
      path: '/imports/rejections',
      name: 'ImportRejections',
      meta: { title: 'Import rejections' },
      component: () => import('../views/ImportRejectionsView.vue'),
    },
    { path: '/imports', name: 'Imports', meta: { title: 'Imports' }, component: () => import('../views/ImportsView.vue') },
    { path: '/reports', name: 'Reports', meta: { title: 'Reports' }, component: () => import('../views/ReportsView.vue') },
    { path: '/reports/data-health', name: 'DataHealth', meta: { title: 'Data Health' }, component: () => import('../views/DataHealthView.vue') },
    { path: '/reports/stock-on-hand-history', name: 'StockOnHandHistory', meta: { title: 'Stock On Hand History' }, component: () => import('../views/StockOnHandHistoryView.vue') },
    { path: '/reports/stock-on-hand-grid', name: 'StockOnHandGrid', meta: { title: 'SOH History Grid' }, component: () => import('../views/StockOnHandGridView.vue') },
    { path: '/reports/sales-grid', name: 'SalesGrid', meta: { title: 'Sales Grid' }, component: () => import('../views/SalesGridView.vue') },
    { path: '/reports/stock-coverage', name: 'StockCoverage', meta: { title: 'Stock Coverage' }, component: () => import('../views/StockCoverageView.vue') },
    { path: '/exports', name: 'Exports', meta: { title: 'Exports' }, component: () => import('../views/ExportsView.vue') },
  ],
})

export default router
